// Generated by nuxt-echarts

import type { BarSeriesOption, GaugeSeriesOption, LineSeriesOption } from 'echarts/charts'
import type {
  DatasetComponentOption,
  GridComponentOption,
  LegendComponentOption,
  MarkPointComponentOption,
  TooltipComponentOption,
} from 'echarts/components'
import type { ComposeOption } from 'echarts/core'

declare global {
  export type ECOption = ComposeOption<
    | BarSeriesOption
    | GaugeSeriesOption
    | LineSeriesOption
    | DatasetComponentOption
    | GridComponentOption
    | TooltipComponentOption
    | LegendComponentOption
    | MarkPointComponentOption
  >
}

export {}
